#!/bin/sh

if [ -z "$TOOLS4J_CLI_HOME" ] ; then
  ## resolve links - $0 may be a link to maven's home
  PRG="$0"

  # need this for relative symlinks
  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
      PRG="$link"
    else
      PRG="`dirname "$PRG"`/$link"
    fi
  done

  saveddir=`pwd`

  TOOLS4J_CLI_HOME=`dirname "$PRG"`/..

  # make it fully qualified
  TOOLS4J_CLI_HOME=`cd "$TOOLS4J_CLI_HOME" && pwd`

  cd "$saveddir"
fi

# "-agentlib:jdwp=transport=dt_socket,server=y,address=147.214.198.11:8011,suspend=y" \

exec java \
  -classpath "${TOOLS4J_CLI_HOME}"/boot/tools4j-cli-bootstrap-*.jar \
  "-Dorg.deephacks.tools4j.cli.home=${TOOLS4J_CLI_HOME}"  \
  org.deephacks.tools4j.cli.Bootstrap "$@"
